let DroneData = [
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 20,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 10,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 10,
      memory: "70.59",
      status: "inactive",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "inactive",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
    {
      id: 1,
      dronename: "1s",
      battery: 80,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 60,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  
    {
      id: 1,
      dronename: "1s",
      battery: 90,
      memory: "70.59",
      status: "active",
      Drone_color: "green",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "2s",
      battery: 80,
      memory: "70.59",
      status: "disable",
      Drone_color: "red",
      Gsm_signal: "good",
    },
    {
      id: 2,
      dronename: "3s",
      battery: 70,
      memory: "70.59",
      status: "active",
      Gsm_signal: "bad",
      // Drone_color : "orange"
    },
  ];
  
  export default DroneData;
  